image: python:3.5

cache:
  paths:
    - .pip
    - .tox

before_script:
  - pip --cache-dir=.pip install tox

flake8:
  script:
    - tox -e flake8

pylint:
  script:
    - tox -e pylint

py27:
  image: python:2.7
  script:
    - tox -e py27
  coverage: '/\S+\.py\s+(?:\d+\s+){4}(\d+\%)/'

py35:
  script:
    - tox -e py35
  coverage: '/\S+\.py\s+(?:\d+\s+){4}(\d+\%)/'
